COMP: Remove GetMTime method
To address:

  d:\a\1\s\include\itkTwoProjectionImageRegistrationMethod.h(204): error C2555: 'itk::TwoProjectionImageRegistrationMethod<InternalImageType,InternalImageType>::GetMTime': overriding virtual function return type differs and is not covariant from 'itk::Object::GetMTime'

If the Set macros are used correctly, this is not necessary.