ENH: Squash history.
Squash previous commits to reduce repository size after the images were
converted to content links.

BUG: Add LICENSE file.

STYLE: Remove executable bit from the sources and images.

ENH: Top level module configuration.

ENH: Populate module include/ directory.

BUG: Fix module dependencies.

ENH: Add initial test/CMakeLists.txt.

COMP: Add missing itkEuler3DTransform header.

Addresses:

/home/matt/src/ITKTwoProjectionRegistration/include/itkSiddonJacobsRayCastInterpolateImageFunction.h:62:11:
error: unknown type name 'Euler3DTransform'
                typedef Euler3DTransform<TCoordRep> TransformType;
                                        ^
                                        /

COMP: A libraries is not generated.

Addresses:

[2/2] Linking CXX executable
/home/matt/bin/ITK-Clang-MinSizeRel/bin/TwoProjectionRegistrationHeaderTest1
FAILED: : && /home/matt/.config/dotfiles/bin/ccache-clang++   -Os -DNDEBUG
CMakeFiles/TwoProjectionRegistrationHeaderTest1.dir/test/TwoProjectionRegistrationHeaderTest1.cxx.o
-o
/home/matt/bin/ITK-Clang-MinSizeRel/bin/TwoProjectionRegistrationHeaderTest1
-rdynamic -lTwoProjectionRegistration
/home/matt/bin/ITK-Clang-MinSizeRel/lib/libitksys-4.9.so.1 -ldl
-Wl,-rpath,/home/matt/bin/ITK-Clang-MinSizeRel/lib && :
/usr/bin/x86_64-pc-linux-gnu-ld: cannot find -lTwoProjectionRegistration

DOC: Address Doxygen group tests.

STYLE: Address numerous style issues.

ENH: Build 2D3DTwoProjRegistration as a test.

COMP: string literal to char * deprecated.

Addresses:

/home/matt/src/ITKTwoProjectionRegistration/test/TwoProjection2D3DRegistration.cxx:142:22:
warning: conversion from string literal to 'char *' is deprecated
[-Wc++11-compat-deprecated-writable-strings]
      char *fileOutput1 = "Image2D1_Registered.tif";
                                  ^
                                  /home/matt/src/ITKTwoProjectionRegistration/test/TwoProjection2D3DRegistration.cxx:143:22:
                                  warning: conversion from string literal to
                                  'char *' is deprecated
                                  [-Wc++11-compat-deprecated-writable-strings]
                                          char *fileOutput2 =
                                          "Image2D2_Registered.tif";
                                                                      ^

ENH: Use content links for the data.

revision 3